# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VrgTechTask' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VrgTechTask
  pod 'SwiftSoup'
  pod 'Alamofire'
  pod 'SnapKit'
  pod 'AlamofireImage'

end
